version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # Adjust this path as needed for your app’s location on the EC2 instance
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
